In [14]:
# CELL 1: IMPORT LIBRARIES AND DEFINE PATHS

import pandas as pd
import os

# Project root = one level above the notebooks folder
BASE_PATH = ".."

RAW_PATH = os.path.join(BASE_PATH, "data", "raw")

TRANS_PATH = os.path.join(RAW_PATH, "LI-Small_Trans.csv")
ACCOUNTS_PATH = os.path.join(RAW_PATH, "LI-Small_accounts.csv")
PATTERNS_PATH = os.path.join(RAW_PATH, "LI-Small_Patterns.txt")

print("Raw data path:", RAW_PATH)

Raw data path: ..\data\raw

In [15]:
# CELL 2: LOAD AND INSPECT LI-SMALL TRANSACTIONS

trans_df = pd.read_csv(TRANS_PATH)

print("TRANSACTION DATASET")
print("=" * 60)

print("Shape:", trans_df.shape)

print("\nColumns:")
for i, col in enumerate(trans_df.columns, 1):
    print(f"{i}. {col}")

print("\nData Types:")
print(trans_df.dtypes)

print("\nFirst 5 rows:")
display(trans_df.head())

print("\nMissing Values:")
print(trans_df.isnull().sum())

print("\nBasic Statistics:")
display(trans_df.describe(include="all").T)

TRANSACTION DATASET
============================================================
Shape: (6924049, 11)

Columns:
1. Timestamp
2. From Bank
3. Account
4. To Bank
5. Account.1
6. Amount Received
7. Receiving Currency
8. Amount Paid
9. Payment Currency
10. Payment Format
11. Is Laundering

Data Types:
Timestamp                 str
From Bank               int64
Account                   str
To Bank                 int64
Account.1                 str
Amount Received       float64
Receiving Currency        str
Amount Paid           float64
Payment Currency          str
Payment Format            str
Is Laundering           int64
dtype: object

First 5 rows:

          Timestamp  From Bank    Account  To Bank  Account.1  Amount Received Receiving Currency  Amount Paid Payment Currency Payment Format  Is Laundering
0  2022/09/01 00:08         11  8000ECA90       11  8000ECA90       3195403.00          US Dollar   3195403.00        US Dollar   Reinvestment              0
1  2022/09/01 00:21       3402  80021DAD0     3402  80021DAD0          1858.96          US Dollar      1858.96        US Dollar   Reinvestment              0
2  2022/09/01 00:00         11  8000ECA90     1120  8006AA910        592571.00          US Dollar    592571.00        US Dollar         Cheque              0
3  2022/09/01 00:16       3814  8006AD080     3814  8006AD080            12.32          US Dollar        12.32        US Dollar   Reinvestment              0
4  2022/09/01 00:00         20  8006AD530       20  8006AD530          2941.56          US Dollar      2941.56        US Dollar   Reinvestment              0

Missing Values:
Timestamp             0
From Bank             0
Account               0
To Bank               0
Account.1             0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        0
Is Laundering         0
dtype: int64

Basic Statistics:

                        count  unique               top     freq            mean                std       min      25%      50%       75%                   max
Timestamp             6924049   14533  2022/09/01 00:22    15221             NaN                NaN       NaN      NaN      NaN       NaN                   NaN
From Bank           6924049.0     NaN               NaN      NaN    59387.184651       90517.001599       0.0    219.0  14195.0  110682.0              376967.0
Account               6924049  681281         10042B660   222037             NaN                NaN       NaN      NaN      NaN       NaN                   NaN
To Bank             6924049.0     NaN               NaN      NaN    84417.017677       90645.616367       0.0  11255.0  29640.0  148040.0              376967.0
Account.1             6924049  576176         10042B660     1553             NaN                NaN       NaN      NaN      NaN       NaN                   NaN
Amount Received     6924049.0     NaN               NaN      NaN  6324066.605183  2105371139.599292  0.000001   174.21  1397.62  12296.33  3644853662746.950195
Receiving Currency    6924049      15         US Dollar  2537242             NaN                NaN       NaN      NaN      NaN       NaN                   NaN
Amount Paid         6924049.0     NaN               NaN      NaN  4676035.972671  1544098506.684122  0.000001   175.38  1399.44  12226.87  3644853662746.950195
Payment Currency      6924049      15         US Dollar  2553887             NaN                NaN       NaN      NaN      NaN       NaN                   NaN
Payment Format        6924049       7            Cheque  2503158             NaN                NaN       NaN      NaN      NaN       NaN                   NaN
Is Laundering       6924049.0     NaN               NaN      NaN        0.000515           0.022685       0.0      0.0      0.0       0.0                   1.0

In [16]:
# CELL 3: LOAD AND INSPECT LI-SMALL ACCOUNTS

accounts_df = pd.read_csv(ACCOUNTS_PATH)

print("ACCOUNTS DATASET")
print("=" * 60)

print("Shape:", accounts_df.shape)

print("\nColumns:")
for i, col in enumerate(accounts_df.columns, 1):
    print(f"{i}. {col}")

print("\nData Types:")
print(accounts_df.dtypes)

print("\nFirst 5 rows:")
display(accounts_df.head())

print("\nMissing Values:")
print(accounts_df.isnull().sum())
# CELL 4: INSPECT LI-SMALL PATTERNS

with open(PATTERNS_PATH, "r", encoding="utf-8") as f:
    pattern_lines = f.readlines()

print("PATTERNS DATASET")
print("=" * 60)

print("Total lines:", len(pattern_lines))

print("\nFirst 40 lines:")
for i, line in enumerate(pattern_lines[:40], 1):
    print(f"{i}: {line.rstrip()}")

# Find pattern types
pattern_headers = [
    line.strip()
    for line in pattern_lines
    if line.startswith("BEGIN LAUNDERING ATTEMPT")
]

print("\nNumber of laundering pattern blocks:", len(pattern_headers))

print("\nPattern headers found:")
for pattern in pattern_headers[:20]:
    print(pattern)
print("\nUnique Values:")
for col in accounts_df.columns:
    print(f"{col}: {accounts_df[col].nunique():,}")

ACCOUNTS DATASET
============================================================
Shape: (712688, 5)

Columns:
1. Bank Name
2. Bank ID
3. Account Number
4. Entity ID
5. Entity Name

Data Types:
Bank Name           str
Bank ID           int64
Account Number      str
Entity ID           str
Entity Name         str
dtype: object

First 5 rows:

                  Bank Name  Bank ID Account Number  Entity ID         Entity Name
0          China Bank #2820   314693      81B86A280  800D8CCF0  Corporation #41344
1         France Bank #4585   311253      8187FEA80  800B505E0  Corporation #54497
2          China Bank #2242    39996      803961E00  800D03F60  Partnership #36904
3  National Bank of Newport   331440      81B075800  801567C10  Corporation #16224
4               UK Bank #33   135417      80CF87C80  801085E00  Partnership #72930

Missing Values:
Bank Name         0
Bank ID           0
Account Number    0
Entity ID         0
Entity Name       0
dtype: int64
PATTERNS DATASET
============================================================
Total lines: 1374

First 40 lines:
1: BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 3-degree Fan-In
2: 2022/09/01 02:38,001812,80279F810,0110,8000A94C0,10154.74,Australian Dollar,10154.74,Australian Dollar,ACH,1
3: 2022/09/02 14:36,022595,80279F8B0,0110,8000A94C0,5326.79,Australian Dollar,5326.79,Australian Dollar,ACH,1
4: 2022/09/03 14:09,001120,800E36A50,0110,8000A94C0,4634.81,Australian Dollar,4634.81,Australian Dollar,ACH,1
5: END LAUNDERING ATTEMPT - FAN-IN
6:
7: BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 8-degree Fan-In
8: 2022/09/01 03:17,003671,801BF8E70,002557,8016B3750,8099.96,Euro,8099.96,Euro,ACH,1
9: 2022/09/01 06:27,015,80074C7E0,002557,8016B3750,10468.56,Euro,10468.56,Euro,ACH,1
10: 2022/09/01 10:04,002557,80107C9A0,002557,8016B3750,10270.07,Euro,10270.07,Euro,ACH,1
11: 2022/09/02 06:35,012,800A9B180,002557,8016B3750,15645.21,Euro,15645.21,Euro,ACH,1
12: 2022/09/03 09:12,021393,801271170,002557,8016B3750,14139.75,Euro,14139.75,Euro,ACH,1
13: 2022/09/03 13:45,002175,801E25F20,002557,8016B3750,6276.26,Euro,6276.26,Euro,ACH,1
14: 2022/09/03 16:17,020,800043BE0,002557,8016B3750,1042.63,Euro,1042.63,Euro,ACH,1
15: 2022/09/03 23:09,022124,8011D0180,002557,8016B3750,12795.57,Euro,12795.57,Euro,ACH,1
16: END LAUNDERING ATTEMPT - FAN-IN
17:
18: BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In
19: 2022/09/01 03:52,023848,801A0BEB0,01835,800F963A0,13573.24,Euro,13573.24,Euro,ACH,1
20: 2022/09/01 05:37,00498,8013B3270,01835,800F963A0,3651.60,Euro,3651.60,Euro,ACH,1
21: 2022/09/02 03:28,00349,80049FE00,01835,800F963A0,6980.43,Euro,6980.43,Euro,ACH,1
22: 2022/09/02 17:21,01835,800F963A0,012386,800F07C90,16003.44,Euro,16003.44,Euro,ACH,1
23: 2022/09/02 19:24,01835,800F963A0,01595,8014DDE40,8201.82,Euro,8201.82,Euro,ACH,1
24: 2022/09/03 11:23,01835,800F963A0,0224,801C56FF0,7648.13,US Dollar,7648.13,US Dollar,ACH,1
25: 2022/09/04 17:18,01835,800F963A0,011,800775EE0,9383.90,Euro,9383.90,Euro,ACH,1
26: 2022/09/05 12:17,01835,800F963A0,02514,80143C140,9340.49,Euro,9340.49,Euro,ACH,1
27: 2022/09/06 17:16,01835,800F963A0,022086,800CD0BE0,18261.63,US Dollar,18261.63,US Dollar,ACH,1
28: END LAUNDERING ATTEMPT - GATHER-SCATTER
29:
30: BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 10 hops
31: 2022/09/01 05:54,011,8001048F0,000,8001B1630,3530.20,Euro,3530.20,Euro,ACH,1
32: 2022/09/01 06:28,000,8001B1630,003,80033F3B0,3530.20,Euro,3530.20,Euro,ACH,1
33: 2022/09/01 10:28,003,80033F3B0,011,8001DC570,4730.57,US Dollar,4730.57,US Dollar,ACH,1
34: 2022/09/01 14:32,011,8001DC570,01768,8007F5C20,4139.13,Euro,4139.13,Euro,ACH,1
35: 2022/09/02 11:51,01768,8007F5C20,01231,800379FA0,4723.36,US Dollar,4723.36,US Dollar,ACH,1
36: 2022/09/02 13:43,01231,800379FA0,003,8001B8080,3849.15,Euro,3849.15,Euro,ACH,1
37: 2022/09/02 19:00,003,8001B8080,001,800161140,4070.87,US Dollar,4070.87,US Dollar,ACH,1
38: 2022/09/03 09:38,001,800161140,00349,800220960,3861.85,US Dollar,3861.85,US Dollar,ACH,1
39: 2022/09/04 01:02,00349,800220960,020,8001F9760,3551.11,US Dollar,3551.11,US Dollar,ACH,1
40: 2022/09/04 12:26,020,8001F9760,0224,800123FE0,3271.85,US Dollar,3271.85,US Dollar,ACH,1

Number of laundering pattern blocks: 117

Pattern headers found:
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 3-degree Fan-In
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 8-degree Fan-In
BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 10 hops
BEGIN LAUNDERING ATTEMPT - SCATTER-GATHER
BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 1-degree Fan-In
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 4 hops
BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 3-degree Fan-Out
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 13-degree Fan-In
BEGIN LAUNDERING ATTEMPT - STACK
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 8-degree Fan-In
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 6-degree Fan-In
BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 15-degree Fan-Out
BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 15-degree Fan-Out
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 11 hops
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 6-degree Fan-In
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 2 hops
BEGIN LAUNDERING ATTEMPT - STACK
BEGIN LAUNDERING ATTEMPT - STACK
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 1 hops

Unique Values:
Bank Name: 27,652
Bank ID: 41,815
Account Number: 712,684
Entity ID: 224,931
Entity Name: 224,931

In [17]:
# CELL 4: INSPECT LI-SMALL PATTERNS

with open(PATTERNS_PATH, "r", encoding="utf-8") as f:
    pattern_lines = f.readlines()

print("PATTERNS DATASET")
print("=" * 60)

print("Total lines:", len(pattern_lines))

print("\nFirst 40 lines:")
for i, line in enumerate(pattern_lines[:40], 1):
    print(f"{i}: {line.rstrip()}")

# Find pattern types
pattern_headers = [
    line.strip()
    for line in pattern_lines
    if line.startswith("BEGIN LAUNDERING ATTEMPT")
]

print("\nNumber of laundering pattern blocks:", len(pattern_headers))

print("\nPattern headers found:")
for pattern in pattern_headers[:20]:
    print(pattern)

PATTERNS DATASET
============================================================
Total lines: 1374

First 40 lines:
1: BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 3-degree Fan-In
2: 2022/09/01 02:38,001812,80279F810,0110,8000A94C0,10154.74,Australian Dollar,10154.74,Australian Dollar,ACH,1
3: 2022/09/02 14:36,022595,80279F8B0,0110,8000A94C0,5326.79,Australian Dollar,5326.79,Australian Dollar,ACH,1
4: 2022/09/03 14:09,001120,800E36A50,0110,8000A94C0,4634.81,Australian Dollar,4634.81,Australian Dollar,ACH,1
5: END LAUNDERING ATTEMPT - FAN-IN
6:
7: BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 8-degree Fan-In
8: 2022/09/01 03:17,003671,801BF8E70,002557,8016B3750,8099.96,Euro,8099.96,Euro,ACH,1
9: 2022/09/01 06:27,015,80074C7E0,002557,8016B3750,10468.56,Euro,10468.56,Euro,ACH,1
10: 2022/09/01 10:04,002557,80107C9A0,002557,8016B3750,10270.07,Euro,10270.07,Euro,ACH,1
11: 2022/09/02 06:35,012,800A9B180,002557,8016B3750,15645.21,Euro,15645.21,Euro,ACH,1
12: 2022/09/03 09:12,021393,801271170,002557,8016B3750,14139.75,Euro,14139.75,Euro,ACH,1
13: 2022/09/03 13:45,002175,801E25F20,002557,8016B3750,6276.26,Euro,6276.26,Euro,ACH,1
14: 2022/09/03 16:17,020,800043BE0,002557,8016B3750,1042.63,Euro,1042.63,Euro,ACH,1
15: 2022/09/03 23:09,022124,8011D0180,002557,8016B3750,12795.57,Euro,12795.57,Euro,ACH,1
16: END LAUNDERING ATTEMPT - FAN-IN
17:
18: BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In
19: 2022/09/01 03:52,023848,801A0BEB0,01835,800F963A0,13573.24,Euro,13573.24,Euro,ACH,1
20: 2022/09/01 05:37,00498,8013B3270,01835,800F963A0,3651.60,Euro,3651.60,Euro,ACH,1
21: 2022/09/02 03:28,00349,80049FE00,01835,800F963A0,6980.43,Euro,6980.43,Euro,ACH,1
22: 2022/09/02 17:21,01835,800F963A0,012386,800F07C90,16003.44,Euro,16003.44,Euro,ACH,1
23: 2022/09/02 19:24,01835,800F963A0,01595,8014DDE40,8201.82,Euro,8201.82,Euro,ACH,1
24: 2022/09/03 11:23,01835,800F963A0,0224,801C56FF0,7648.13,US Dollar,7648.13,US Dollar,ACH,1
25: 2022/09/04 17:18,01835,800F963A0,011,800775EE0,9383.90,Euro,9383.90,Euro,ACH,1
26: 2022/09/05 12:17,01835,800F963A0,02514,80143C140,9340.49,Euro,9340.49,Euro,ACH,1
27: 2022/09/06 17:16,01835,800F963A0,022086,800CD0BE0,18261.63,US Dollar,18261.63,US Dollar,ACH,1
28: END LAUNDERING ATTEMPT - GATHER-SCATTER
29:
30: BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 10 hops
31: 2022/09/01 05:54,011,8001048F0,000,8001B1630,3530.20,Euro,3530.20,Euro,ACH,1
32: 2022/09/01 06:28,000,8001B1630,003,80033F3B0,3530.20,Euro,3530.20,Euro,ACH,1
33: 2022/09/01 10:28,003,80033F3B0,011,8001DC570,4730.57,US Dollar,4730.57,US Dollar,ACH,1
34: 2022/09/01 14:32,011,8001DC570,01768,8007F5C20,4139.13,Euro,4139.13,Euro,ACH,1
35: 2022/09/02 11:51,01768,8007F5C20,01231,800379FA0,4723.36,US Dollar,4723.36,US Dollar,ACH,1
36: 2022/09/02 13:43,01231,800379FA0,003,8001B8080,3849.15,Euro,3849.15,Euro,ACH,1
37: 2022/09/02 19:00,003,8001B8080,001,800161140,4070.87,US Dollar,4070.87,US Dollar,ACH,1
38: 2022/09/03 09:38,001,800161140,00349,800220960,3861.85,US Dollar,3861.85,US Dollar,ACH,1
39: 2022/09/04 01:02,00349,800220960,020,8001F9760,3551.11,US Dollar,3551.11,US Dollar,ACH,1
40: 2022/09/04 12:26,020,8001F9760,0224,800123FE0,3271.85,US Dollar,3271.85,US Dollar,ACH,1

Number of laundering pattern blocks: 117

Pattern headers found:
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 3-degree Fan-In
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 8-degree Fan-In
BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 10 hops
BEGIN LAUNDERING ATTEMPT - SCATTER-GATHER
BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 1-degree Fan-In
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 4 hops
BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 3-degree Fan-Out
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 13-degree Fan-In
BEGIN LAUNDERING ATTEMPT - STACK
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 8-degree Fan-In
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 6-degree Fan-In
BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 15-degree Fan-Out
BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 15-degree Fan-Out
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 11 hops
BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 6-degree Fan-In
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 2 hops
BEGIN LAUNDERING ATTEMPT - STACK
BEGIN LAUNDERING ATTEMPT - STACK
BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 1 hops

In [18]:
# CELL 5: ACCOUNT AND BANK IDENTIFIER INSPECTION

print("ACCOUNT IDENTIFIER INSPECTION")
print("=" * 60)

# ---------------------------------------------------------
# 1. Account Number uniqueness
# ---------------------------------------------------------

account_unique = accounts_df["Account Number"].nunique()
account_rows = len(accounts_df)

print(f"Total account records: {account_rows:,}")
print(f"Unique Account Numbers: {account_unique:,}")
print(f"Duplicate Account Number records: {account_rows - account_unique:,}")

# ---------------------------------------------------------
# 2. (Bank ID, Account Number) uniqueness
# ---------------------------------------------------------

bank_account_unique = accounts_df[
    ["Bank ID", "Account Number"]
].drop_duplicates().shape[0]

print(f"\nUnique (Bank ID, Account Number): {bank_account_unique:,}")

if bank_account_unique == account_rows:
    print("RESULT: (Bank ID, Account Number) uniquely identifies an account.")
else:
    print("RESULT: (Bank ID, Account Number) still contains duplicates.")

# ---------------------------------------------------------
# 3. Transaction → Accounts bank matching
# ---------------------------------------------------------

transaction_from_banks = set(trans_df["From Bank"].astype(str))
transaction_to_banks = set(trans_df["To Bank"].astype(str))

account_bank_ids = set(accounts_df["Bank ID"].astype(str))

from_matches = transaction_from_banks.intersection(account_bank_ids)
to_matches = transaction_to_banks.intersection(account_bank_ids)

print("\nTRANSACTION → ACCOUNT BANK MATCHING")
print("-" * 60)

print(
    f"Unique From Bank IDs in transactions: "
    f"{len(transaction_from_banks):,}"
)

print(
    f"Matched From Bank IDs: "
    f"{len(from_matches):,}"
)

print(
    f"Unique To Bank IDs in transactions: "
    f"{len(transaction_to_banks):,}"
)

print(
    f"Matched To Bank IDs: "
    f"{len(to_matches):,}"
)

# ---------------------------------------------------------
# 4. Bank identifier inspection
# ---------------------------------------------------------

unique_bank_names = accounts_df["Bank Name"].nunique()
unique_bank_ids = accounts_df["Bank ID"].nunique()
unique_bank_pairs = accounts_df[
    ["Bank Name", "Bank ID"]
].drop_duplicates().shape[0]

print("\nBANK IDENTIFIER INSPECTION")
print("-" * 60)

print(f"Unique Bank Names: {unique_bank_names:,}")
print(f"Unique Bank IDs: {unique_bank_ids:,}")
print(f"Unique Bank Name + Bank ID pairs: {unique_bank_pairs:,}")

# ---------------------------------------------------------
# 5. Check whether one Bank ID has multiple Bank Names
# ---------------------------------------------------------

bank_id_name_counts = (
    accounts_df.groupby("Bank ID")["Bank Name"]
    .nunique()
)

multiple_names_per_id = bank_id_name_counts[
    bank_id_name_counts > 1
]

print(
    f"\nBank IDs with multiple Bank Names: "
    f"{len(multiple_names_per_id):,}"
)

# ---------------------------------------------------------
# 6. Final conclusion
# ---------------------------------------------------------

print("\nFINAL IDENTIFIER CONCLUSION")
print("=" * 60)

print("Account identity:")
print("(Bank ID, Account Number)")

print("\nBank identity:")
print("Bank ID")

print("\nBank Name:")
print("Descriptive attribute, NOT the primary bank identifier.")

ACCOUNT IDENTIFIER INSPECTION
============================================================
Total account records: 712,688
Unique Account Numbers: 712,684
Duplicate Account Number records: 4

Unique (Bank ID, Account Number): 712,688
RESULT: (Bank ID, Account Number) uniquely identifies an account.

TRANSACTION → ACCOUNT BANK MATCHING
------------------------------------------------------------
Unique From Bank IDs in transactions: 41,814
Matched From Bank IDs: 41,814
Unique To Bank IDs in transactions: 21,588
Matched To Bank IDs: 21,588

BANK IDENTIFIER INSPECTION
------------------------------------------------------------
Unique Bank Names: 27,652
Unique Bank IDs: 41,815
Unique Bank Name + Bank ID pairs: 41,815

Bank IDs with multiple Bank Names: 0

FINAL IDENTIFIER CONCLUSION
============================================================
Account identity:
(Bank ID, Account Number)

Bank identity:
Bank ID

Bank Name:
Descriptive attribute, NOT the primary bank identifier.