In [1]:
# CELL 1: LOAD RAW TRANSACTIONS

import pandas as pd
import os

BASE_PATH = ".."

RAW_PATH = os.path.join(
    BASE_PATH, "data", "raw"
)

PROCESSED_PATH = os.path.join(
    BASE_PATH, "data", "processed"
)

TRANS_PATH = os.path.join(
    RAW_PATH, "LI-Small_Trans.csv"
)

os.makedirs(PROCESSED_PATH, exist_ok=True)

trans_df = pd.read_csv(TRANS_PATH)

print("Raw transaction dataset loaded.")
print("Shape:", trans_df.shape)

display(trans_df.head())

Raw transaction dataset loaded.
Shape: (6924049, 11)

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3195403.00,US Dollar,3195403.00,US Dollar,Reinvestment,0
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1858.96,US Dollar,1858.96,US Dollar,Reinvestment,0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,592571.00,US Dollar,592571.00,US Dollar,Cheque,0
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,12.32,US Dollar,12.32,US Dollar,Reinvestment,0
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2941.56,US Dollar,2941.56,US Dollar,Reinvestment,0

In [2]:
# CELL 2: VALIDATE TRANSACTION DATA AND CREATE TRANSACTION ID

expected_columns = [
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering"
]

# Check columns
missing_columns = [
    col for col in expected_columns
    if col not in trans_df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing columns: {missing_columns}"
    )

# Reorder columns exactly as required
trans_df = trans_df[expected_columns].copy()

# Create transaction ID
trans_df.insert(
    0,
    "Transaction ID",
    range(1, len(trans_df) + 1)
)

print("Columns validated.")
print("Transaction IDs created.")

print("\nShape:", trans_df.shape)

print("\nDuplicate Transaction IDs:",
      trans_df["Transaction ID"].duplicated().sum())

display(trans_df.head())

Columns validated.
Transaction IDs created.

Shape: (6924049, 12)

Duplicate Transaction IDs: 0

,Transaction ID,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,1,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3195403.00,US Dollar,3195403.00,US Dollar,Reinvestment,0
1,2,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1858.96,US Dollar,1858.96,US Dollar,Reinvestment,0
2,3,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,592571.00,US Dollar,592571.00,US Dollar,Cheque,0
3,4,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,12.32,US Dollar,12.32,US Dollar,Reinvestment,0
4,5,2022/09/01 00:00,20,8006AD530,20,8006AD530,2941.56,US Dollar,2941.56,US Dollar,Reinvestment,0

In [3]:
# CELL 3: VALIDATE FINAL TRANSACTIONS DATASET

print("TRANSACTIONS DATASET VALIDATION")
print("=" * 60)

print("Rows:", f"{len(trans_df):,}")
print("Columns:", len(trans_df.columns))

print("\nMissing values:")
print(trans_df.isnull().sum())

print("\nClass distribution:")
print(
    trans_df["Is Laundering"]
    .value_counts()
    .rename(index={
        0: "Normal",
        1: "Laundering"
    })
)

print("\nUnique Transaction IDs:",
      trans_df["Transaction ID"].nunique())

print("\nExpected rows:",
      f"{len(trans_df):,}")

print("\nExpected columns:")
for i, col in enumerate(trans_df.columns, 1):
    print(f"{i}. {col}")

TRANSACTIONS DATASET VALIDATION
============================================================
Rows: 6,924,049
Columns: 12

Missing values:
Transaction ID        0
Timestamp             0
From Bank             0
Account               0
To Bank               0
Account.1             0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        0
Is Laundering         0
dtype: int64

Class distribution:
Is Laundering
Normal        6920484
Laundering       3565
Name: count, dtype: int64

Unique Transaction IDs: 6924049

Expected rows: 6,924,049

Expected columns:
1. Transaction ID
2. Timestamp
3. From Bank
4. Account
5. To Bank
6. Account.1
7. Amount Received
8. Receiving Currency
9. Amount Paid
10. Payment Currency
11. Payment Format
12. Is Laundering

In [4]:
# CELL 4: SAVE PROCESSED TRANSACTIONS DATASET

OUTPUT_PATH = os.path.join(
    PROCESSED_PATH,
    "transactions.csv"
)

trans_df.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Transactions dataset saved successfully.")
print("\nLocation:")
print(OUTPUT_PATH)

print("\nFinal shape:")
print(trans_df.shape)

Transactions dataset saved successfully.

Location:
..\data\processed\transactions.csv

Final shape:
(6924049, 12)