In [1]:
import pandas as pd

# ============================================================
# 1. LOAD ORIGINAL DATASET FROM RAW
# ============================================================

raw_path = "../data/raw/LI-Small_Trans.csv"

trans_df = pd.read_csv(
    raw_path,
    usecols=["Timestamp"]
)

print("Raw dataset loaded successfully.")
print("Total timestamps:", len(trans_df))


# ============================================================
# 2. SHOW EXAMPLES FROM RAW DATA
# ============================================================

print("\nFirst 10 raw timestamps:")
print(trans_df["Timestamp"].head(10).to_string(index=False))


# ============================================================
# 3. CHECK EXACT EXPECTED FORMAT
# ============================================================

expected_format = "%Y/%m/%d %H:%M"

parsed_timestamp = pd.to_datetime(
    trans_df["Timestamp"],
    format=expected_format,
    errors="coerce"
)


# ============================================================
# 4. CHECK INVALID TIMESTAMPS
# ============================================================

invalid_mask = parsed_timestamp.isna()

invalid_count = invalid_mask.sum()
valid_count = (~invalid_mask).sum()

print("\nTimestamp validation:")
print("Valid timestamps  :", valid_count)
print("Invalid timestamps:", invalid_count)


# ============================================================
# 5. SHOW INVALID VALUES IF ANY
# ============================================================

if invalid_count > 0:

    print("\nINVALID TIMESTAMP EXAMPLES:")

    print(
        trans_df.loc[invalid_mask, "Timestamp"]
        .head(20)
        .to_string(index=False)
    )

else:

    print("\nALL timestamps match the exact format:")
    print("YYYY/MM/DD HH:MM")


# ============================================================
# 6. CHECK THE DATE ORDER
# ============================================================

print("\nDate interpretation:")
print("Year  :", parsed_timestamp.dt.year.min(), "to", parsed_timestamp.dt.year.max())
print("Month :", parsed_timestamp.dt.month.min(), "to", parsed_timestamp.dt.month.max())
print("Day   :", parsed_timestamp.dt.day.min(), "to", parsed_timestamp.dt.day.max())


# ============================================================
# 7. SHOW PARSED EXAMPLES
# ============================================================

print("\nRaw → Parsed examples:")

check_df = pd.DataFrame({
    "Raw Timestamp": trans_df["Timestamp"].head(10),
    "Parsed Timestamp": parsed_timestamp.head(10)
})

print(check_df.to_string(index=False))


# ============================================================
# 8. FINAL RESULT
# ============================================================

if invalid_count == 0:

    print("\n" + "=" * 60)
    print("TIMESTAMP CHECK PASSED")
    print("=" * 60)

    print("Format confirmed: YYYY/MM/DD HH:MM")
    print("Python/Pandas format:", expected_format)
    print("Example:", trans_df["Timestamp"].iloc[0])

else:

    print("\n" + "=" * 60)
    print("TIMESTAMP CHECK FAILED")
    print("=" * 60)

    print("Some timestamps do not match the expected format.")
    print("DO NOT generate temporal features until they are checked.")

Raw dataset loaded successfully.
Total timestamps: 6924049

First 10 raw timestamps:
2022/09/01 00:08
2022/09/01 00:21
2022/09/01 00:00
2022/09/01 00:16
2022/09/01 00:00
2022/09/01 00:24
2022/09/01 00:17
2022/09/01 00:07
2022/09/01 00:28
2022/09/01 00:22

Timestamp validation:
Valid timestamps  : 6924049
Invalid timestamps: 0

ALL timestamps match the exact format:
YYYY/MM/DD HH:MM

Date interpretation:
Year  : 2022 to 2022
Month : 9 to 9
Day   : 1 to 17

Raw → Parsed examples:
   Raw Timestamp    Parsed Timestamp
2022/09/01 00:08 2022-09-01 00:08:00
2022/09/01 00:21 2022-09-01 00:21:00
2022/09/01 00:00 2022-09-01 00:00:00
2022/09/01 00:16 2022-09-01 00:16:00
2022/09/01 00:00 2022-09-01 00:00:00
2022/09/01 00:24 2022-09-01 00:24:00
2022/09/01 00:17 2022-09-01 00:17:00
2022/09/01 00:07 2022-09-01 00:07:00
2022/09/01 00:28 2022-09-01 00:28:00
2022/09/01 00:22 2022-09-01 00:22:00

============================================================
TIMESTAMP CHECK PASSED
============================================================
Format confirmed: YYYY/MM/DD HH:MM
Python/Pandas format: %Y/%m/%d %H:%M
Example: 2022/09/01 00:08

In [2]:
import os
import gc
import time

import numpy as np
import pandas as pd
from pandas.api.types import union_categoricals

BASE_PATH = ".."
RAW_PATH = os.path.join(BASE_PATH, "data", "raw")
PROCESSED_PATH = os.path.join(BASE_PATH, "data", "processed")
os.makedirs(PROCESSED_PATH, exist_ok=True)

TRANS_FILE = os.path.join(RAW_PATH, "LI-Small_Trans.csv")          # the ONLY data source
ACCOUNTS_FILE = os.path.join(RAW_PATH, "LI-Small_accounts.csv")   # optional validation only
OUTPUT_FILE = os.path.join(PROCESSED_PATH, "temporal_features.csv")
BACKUP_FILE = os.path.join(PROCESSED_PATH, "temporal_features_8col_backup.csv")
BACKUP_OLD_FILE = False        # if an old temporal_features.csv exists, rename it to the backup name instead of overwriting it

TIMESTAMP_FORMAT = "%Y/%m/%d %H:%M"      # e.g. 2022/09/01 00:08

# Window lengths in seconds
WINDOW_10M = 10 * 60
WINDOW_30M = 30 * 60
WINDOW_1H = 60 * 60
WINDOW_24H = 24 * 60 * 60
WINDOW_7D = 7 * 24 * 60 * 60

ACCOUNT_AGE_BASIS = "any"     # "any": first appearance as sender OR receiver | "sender": first outgoing transaction

FINAL_COLUMNS = [
    "Transaction ID",
    "Sender Account ID",
    "Receiver Account ID",
    "Transactions Last 10 Minutes",
    "Transactions Last 30 Minutes",
    "Transactions Last 1 Hour",
    "Transactions Last 24 Hours",
    "Transactions Last 7 Days",
    "Amount Last 24 Hours",
    "Time Since Previous Transaction",
    "Account Age Before Transaction",
    "Transactions Since First Seen",
    "Amount Since First Seen",
    "Average Amount Last 24 Hours",
    "Transactions Last 10 Minutes Receiver",
]
assert len(FINAL_COLUMNS) == 15

print("Transactions file:", os.path.abspath(TRANS_FILE))
print("Output file      :", os.path.abspath(OUTPUT_FILE))

Transactions file: e:\AML-GNN-Project\data\raw\LI-Small_Trans.csv
Output file      : e:\AML-GNN-Project\data\processed\temporal_features.csv

In [3]:
t_start = time.time()

USE_COLS = ["Timestamp", "From Bank", "Account", "To Bank", "Account.1", "Amount Paid"]

df = pd.read_csv(
    TRANS_FILE,
    usecols=USE_COLS,
    dtype={
        "Timestamp": "string",
        "From Bank": "string",
        "Account": "string",
        "To Bank": "string",
        "Account.1": "string",
        "Amount Paid": "float64",
    },
)
df = df[USE_COLS]   # fixed column order

N_RAW = len(df)
print(f"Rows loaded : {N_RAW:,}")
print(f"Columns     : {list(df.columns)}")
print(f"Memory usage: {df.memory_usage(deep=True).sum() / 1024**2:,.1f} MB")
print(f"Load time   : {time.time() - t_start:,.1f} s")
df.head()

Rows loaded : 6,924,049
Columns     : ['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1', 'Amount Paid']
Memory usage: 1,973.5 MB
Load time   : 8.6 s

          Timestamp From Bank    Account To Bank  Account.1  Amount Paid
0  2022/09/01 00:08       011  8000ECA90     011  8000ECA90   3195403.00
1  2022/09/01 00:21     03402  80021DAD0   03402  80021DAD0      1858.96
2  2022/09/01 00:00       011  8000ECA90  001120  8006AA910    592571.00
3  2022/09/01 00:16     03814  8006AD080   03814  8006AD080        12.32
4  2022/09/01 00:00       020  8006AD530     020  8006AD530      2941.56

In [4]:
# Transaction ID = original raw-file order (1..N). Created BEFORE any sorting.
df.insert(0, "Transaction ID", np.arange(1, N_RAW + 1, dtype=np.int64))

# Missing components would produce broken IDs, so check first
for col in ["From Bank", "Account", "To Bank", "Account.1"]:
    n_missing = int(df[col].isna().sum())
    if n_missing:
        raise ValueError(f"Column '{col}' has {n_missing:,} missing values; cannot build Account IDs.")

# Account ID = Bank + "_" + Account Number
df["Sender Account ID"] = df["From Bank"] + "_" + df["Account"]
df["Receiver Account ID"] = df["To Bank"] + "_" + df["Account.1"]

# Free the raw component columns
df.drop(columns=["From Bank", "Account", "To Bank", "Account.1"], inplace=True)

# Category dtype: each distinct ID string is stored once, and gives integer codes for fast sorting
df["Sender Account ID"] = df["Sender Account ID"].astype("category")
df["Receiver Account ID"] = df["Receiver Account ID"].astype("category")
gc.collect()

# Verify Transaction ID
assert df["Transaction ID"].is_unique, "Transaction ID is not unique"
assert df["Transaction ID"].iloc[0] == 1 and df["Transaction ID"].iloc[-1] == N_RAW
assert (np.diff(df["Transaction ID"].to_numpy()) == 1).all(), "Transaction ID is not 1..N"

print(f"Transaction ID range : 1 -> {N_RAW:,} (unique, consecutive)")
print(f"Unique sender accounts  : {df['Sender Account ID'].nunique():,}")
print(f"Unique receiver accounts: {df['Receiver Account ID'].nunique():,}")
print(f"Memory usage: {df.memory_usage(deep=True).sum() / 1024**2:,.1f} MB")
df.head()

Transaction ID range : 1 -> 6,924,049 (unique, consecutive)
Unique sender accounts  : 681,283
Unique receiver accounts: 576,178
Memory usage: 666.1 MB

,Transaction ID,Timestamp,Amount Paid,Sender Account ID,Receiver Account ID
0,1,2022/09/01 00:08,3195403.00,011_8000ECA90,011_8000ECA90
1,2,2022/09/01 00:21,1858.96,03402_80021DAD0,03402_80021DAD0
2,3,2022/09/01 00:00,592571.00,011_8000ECA90,001120_8006AA910
3,4,2022/09/01 00:16,12.32,03814_8006AD080,03814_8006AD080
4,5,2022/09/01 00:00,2941.56,020_8006AD530,020_8006AD530

In [5]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"], format=TIMESTAMP_FORMAT, errors="coerce")

invalid_mask = df["Timestamp"].isna()
N_INVALID = int(invalid_mask.sum())
print(f"Invalid timestamps: {N_INVALID:,}")

# A very high invalid count means the format is wrong, not that the data is bad
if N_INVALID > 0.01 * N_RAW:
    raise ValueError(
        f"{N_INVALID:,} of {N_RAW:,} timestamps failed to parse with format '{TIMESTAMP_FORMAT}'. "
        "Inspect the raw Timestamp strings and adjust TIMESTAMP_FORMAT."
    )

# Explicit handling: invalid rows are excluded (reported, never silent)
EXCLUDED_TRANSACTION_IDS = np.array([], dtype=np.int64)
if N_INVALID > 0:
    EXCLUDED_TRANSACTION_IDS = df.loc[invalid_mask, "Transaction ID"].to_numpy()
    print("Excluded Transaction IDs (first 20):", EXCLUDED_TRANSACTION_IDS[:20])
    df = df.loc[~invalid_mask].reset_index(drop=True)
    print(f"Rows excluded from temporal features: {N_INVALID:,}")
    print("Note: Transaction IDs keep their ORIGINAL raw-file numbering, so gaps will exist.")

N_VALID = len(df)
print(f"Valid rows        : {N_VALID:,}")
print(f"Minimum timestamp : {df['Timestamp'].min()}")
print(f"Maximum timestamp : {df['Timestamp'].max()}")

del invalid_mask
gc.collect()

Invalid timestamps: 0
Valid rows        : 6,924,049
Minimum timestamp : 2022-09-01 00:00:00
Maximum timestamp : 2022-09-17 15:28:00

0

In [6]:
# ---------------------------------------------------------------
# Plain NumPy arrays for the computation. One shared integer code per account, used for BOTH the
# sender and the receiver column, so that "the same account" has the same code on either side.
# ---------------------------------------------------------------
union = union_categoricals([df["Sender Account ID"], df["Receiver Account ID"]])
all_codes = union.codes.astype(np.int64)
sender_codes = all_codes[:N_VALID].copy()
receiver_codes = all_codes[N_VALID:].copy()
del union, all_codes

ts_sec = df["Timestamp"].to_numpy().astype("datetime64[s]").astype(np.int64)      # epoch seconds
amount_paid = df["Amount Paid"].to_numpy(dtype=np.float64, copy=True)
n_missing_amount = int(np.isnan(amount_paid).sum())
if n_missing_amount:
    print(f"WARNING: {n_missing_amount:,} missing Amount Paid values treated as 0.")
    amount_paid = np.nan_to_num(amount_paid, nan=0.0)
tid = df["Transaction ID"].to_numpy(dtype=np.int64)

print(f"Rows: {N_VALID:,} | distinct account codes: {int(max(sender_codes.max(), receiver_codes.max())) + 1:,}")
print("Raw file order is NOT chronological: share of rows whose timestamp is earlier than the previous row's:",
      f"{float(np.mean(np.diff(ts_sec) < 0)):.2%}")

Rows: 6,924,049 | distinct account codes: 705,907
Raw file order is NOT chronological: share of rows whose timestamp is earlier than the previous row's: 47.64%

In [7]:
def restore(x_sorted, order):
    out = np.empty_like(x_sorted)
    out[order] = x_sorted
    return out


def compute_temporal_features(sender_codes, receiver_codes, ts_sec, amount_paid, tid, age_basis="any", verbose=False):
    """All 12 numeric temporal features, returned as a dict of arrays in the ORIGINAL row order.
    Every value only uses transactions with a strictly earlier timestamp (see the window rule above)."""
    t0 = time.time()
    n = len(ts_sec)
    t_min = int(ts_sec.min())
    M = (int(ts_sec.max()) - t_min) + 2 * WINDOW_7D + 10       # wider than any account block
    n_codes = int(max(sender_codes.max(), receiver_codes.max())) + 1
    assert n_codes * M < 2**62, "Composite key would overflow int64"

    # ======================= SENDER SIDE =======================
    # Sort key (sender, timestamp, Transaction ID). The WINDOW_7D offset keeps (key - window) inside the account's own block.
    order = np.lexsort((tid, ts_sec, sender_codes))
    s, t, a = sender_codes[order], ts_sec[order], amount_paid[order]
    key = s * M + (t - t_min + WINDOW_7D)
    block_start = np.searchsorted(s, s, side="left")              # first row of this sender
    right = np.searchsorted(key, key, side="left")                # first row of the current timestamp -> same-minute rows excluded

    def count_window(W):
        left = np.searchsorted(key, key - W, side="right")        # first row strictly later than t - W
        return left, right - left

    left_10m, c10 = count_window(WINDOW_10M)
    left_30m, c30 = count_window(WINDOW_30M)
    left_1h, c1h = count_window(WINDOW_1H)
    left_24h, c24 = count_window(WINDOW_24H)
    left_7d, c7d = count_window(WINDOW_7D)

    # exclusive per-sender prefix sum of Amount Paid: prefix[j] = amount sent by this sender in its rows before j
    prefix = pd.Series(a).groupby(s, sort=False).cumsum().to_numpy() - a
    amt24 = np.maximum(prefix[right] - prefix[left_24h], 0.0)
    since_cnt = right - block_start                               # all earlier outgoing transactions
    since_amt = np.maximum(prefix[right], 0.0)                    # all earlier outgoing amount
    avg24 = np.divide(amt24, c24, out=np.zeros(n), where=c24 > 0)

    # Time since previous transaction (seconds): previous row of the same sender in (timestamp, Transaction ID) order; NaN for the first
    tsp = np.full(n, np.nan)
    idx = np.flatnonzero(s[1:] == s[:-1]) + 1
    tsp[idx] = (t[idx] - t[idx - 1]).astype(np.float64)

    # Account age (seconds since the account's first observed transaction; that moment is never later than now)
    if age_basis == "sender":
        first_ts = t[block_start]
    else:
        codes_both = np.concatenate([sender_codes, receiver_codes])
        ts_both = np.concatenate([ts_sec, ts_sec])
        gb = pd.Series(ts_both).groupby(codes_both).min()
        first_arr = np.zeros(n_codes, dtype=np.int64)
        first_arr[gb.index.to_numpy()] = gb.to_numpy()
        first_ts = first_arr[s]
        del codes_both, ts_both, gb, first_arr
    age = t - first_ts
    if verbose: print(f"   sender side done ({time.time() - t0:.1f}s)")

    res = {
        "c10": restore(c10, order).astype(np.int32), "c30": restore(c30, order).astype(np.int32),
        "c1h": restore(c1h, order).astype(np.int32), "c24": restore(c24, order).astype(np.int32),
        "c7d": restore(c7d, order).astype(np.int32), "amt24": restore(amt24, order),
        "tsp": restore(tsp, order), "age": restore(age, order),
        "since_cnt": restore(since_cnt, order).astype(np.int32), "since_amt": restore(since_amt, order),
        "avg24": restore(avg24, order),
    }
    del s, t, a, key, block_start, right, left_10m, left_30m, left_1h, left_24h, left_7d, prefix, order
    gc.collect()

    # ======================= RECEIVER SIDE (column 15) =======================
    # How many transactions did the RECEIVING account receive in the 10 minutes before this transaction?
    order_r = np.lexsort((tid, ts_sec, receiver_codes))
    r, tr = receiver_codes[order_r], ts_sec[order_r]
    key_r = r * M + (tr - t_min + WINDOW_7D)
    right_r = np.searchsorted(key_r, key_r, side="left")
    left_r = np.searchsorted(key_r, key_r - WINDOW_10M, side="right")
    res["rcv10"] = restore(right_r - left_r, order_r).astype(np.int32)
    del r, tr, key_r, right_r, left_r, order_r
    gc.collect()
    if verbose: print(f"   receiver side done ({time.time() - t0:.1f}s)")
    return res

print("compute_temporal_features() defined")

compute_temporal_features() defined

In [8]:
t_start = time.time()
res = compute_temporal_features(sender_codes, receiver_codes, ts_sec, amount_paid, tid, ACCOUNT_AGE_BASIS, verbose=True)

temporal_features = pd.DataFrame({
    "Transaction ID": df["Transaction ID"].to_numpy(),
    "Sender Account ID": df["Sender Account ID"],
    "Receiver Account ID": df["Receiver Account ID"],
    "Transactions Last 10 Minutes": res["c10"],
    "Transactions Last 30 Minutes": res["c30"],
    "Transactions Last 1 Hour": res["c1h"],
    "Transactions Last 24 Hours": res["c24"],
    "Transactions Last 7 Days": res["c7d"],
    "Amount Last 24 Hours": res["amt24"].round(2),
    "Time Since Previous Transaction": res["tsp"],        # seconds, NaN for a sender's first transaction
    "Account Age Before Transaction": res["age"],         # seconds
    "Transactions Since First Seen": res["since_cnt"],
    "Amount Since First Seen": res["since_amt"].round(2),
    "Average Amount Last 24 Hours": res["avg24"].round(4),
    "Transactions Last 10 Minutes Receiver": res["rcv10"],
})[FINAL_COLUMNS]

# Rows are in raw-file order; make sure
assert temporal_features["Transaction ID"].is_monotonic_increasing, "Transaction ID order broken"

# Debug-only series (NOT part of the output), aligned by index
ts_debug = df["Timestamp"]
amt_debug = df["Amount Paid"].fillna(0.0)

print(f"\ntemporal_features shape: {temporal_features.shape}")
print(f"Memory usage: {temporal_features.memory_usage(deep=True).sum() / 1024**2:,.1f} MB")
print(f"Computed in {time.time() - t_start:,.1f} s")

   sender side done (4.0s)
   receiver side done (6.2s)

temporal_features shape: (6924049, 15)
Memory usage: 633.0 MB
Computed in 7.0 s

In [9]:
RUN_ACCOUNTS_COVERAGE = False   # set True only if you want the (slower) LI-Small_accounts.csv check
N_SAMPLE_ACCOUNTS = 25

def tick(label, t0):
    print(f"   [{time.time() - t0:5.1f} s] {label}")

T0 = time.time()
print("=" * 70)
print("VALIDATION")
print("=" * 70)

tf = temporal_features   # alias, no copy

# --- Row count -------------------------------------------------------
print(f"Raw rows                : {N_RAW:,}")
print(f"Invalid timestamps      : {N_INVALID:,} (excluded)")
print(f"Valid rows              : {N_VALID:,}")
print(f"temporal_features rows  : {len(tf):,}")
assert len(tf) == N_VALID
assert N_VALID + N_INVALID == N_RAW
print("OK: rows == valid transaction rows")

# --- Transaction ID --------------------------------------------------
tid_arr = tf["Transaction ID"].to_numpy()
assert (np.diff(tid_arr) > 0).all()
print("OK: Transaction ID is unique and ascending")
if N_INVALID == 0:
    assert tid_arr[0] == 1 and tid_arr[-1] == N_RAW
    print(f"OK: Transaction ID covers 1..{N_RAW:,}")

# --- Schema ----------------------------------------------------------
assert list(tf.columns) == FINAL_COLUMNS
print("OK: exactly the 15 required columns, in the required order")
tick("schema / IDs", T0)

# --- Numeric columns as arrays ----------------------------------------
c10 = tf["Transactions Last 10 Minutes"].to_numpy(); c30 = tf["Transactions Last 30 Minutes"].to_numpy()
c1 = tf["Transactions Last 1 Hour"].to_numpy(); c24 = tf["Transactions Last 24 Hours"].to_numpy(); c7 = tf["Transactions Last 7 Days"].to_numpy()
amt = tf["Amount Last 24 Hours"].to_numpy(); tsp = tf["Time Since Previous Transaction"].to_numpy()
age = tf["Account Age Before Transaction"].to_numpy(); since_cnt = tf["Transactions Since First Seen"].to_numpy()
since_amt = tf["Amount Since First Seen"].to_numpy(); avg24 = tf["Average Amount Last 24 Hours"].to_numpy()
rcv10 = tf["Transactions Last 10 Minutes Receiver"].to_numpy()

# --- Missing values --------------------------------------------------
n_nan_tsp = int(np.isnan(tsp).sum())
n_unique_senders = int(np.unique(sender_codes).size)
print("\nMissing values per column:")
print(tf.isna().sum().to_string())
print(f"\nUnique senders: {n_unique_senders:,} | NaN in Time Since Previous: {n_nan_tsp:,}")
assert n_nan_tsp == n_unique_senders, "NaN should appear exactly once per sender"
assert not tf[[c for c in FINAL_COLUMNS if c != "Time Since Previous Transaction"]].isna().any().any()
print("OK: NaN only in Time Since Previous Transaction, exactly once per sender")
tick("missing values", T0)

# --- Numeric validity / logical relations ------------------------------
for name, arr in [("c10", c10), ("c30", c30), ("c1", c1), ("c24", c24), ("c7", c7), ("amt", amt), ("age", age),
                  ("since_cnt", since_cnt), ("since_amt", since_amt), ("avg24", avg24), ("rcv10", rcv10)]:
    assert (arr >= 0).all(), f"negative values in {name}"
assert (tsp[~np.isnan(tsp)] >= 0).all()
print("OK: all counts / amounts / times are >= 0")
assert (c10 <= c30).all() and (c30 <= c1).all() and (c1 <= c24).all() and (c24 <= c7).all()
print("OK: 10 min <= 30 min <= 1 hour <= 24 hours <= 7 days for every row")
assert (c7 <= since_cnt).all()
print("OK: Transactions Last 7 Days <= Transactions Since First Seen")
assert (amt <= since_amt + 1e-6).all()
print("OK: Amount Last 24 Hours <= Amount Since First Seen")
assert (amt[c24 == 0] == 0).all() and (avg24[c24 == 0] == 0).all()
print("OK: zero 24h count -> zero 24h amount and zero 24h average")
m = c24 > 0
assert np.allclose(avg24[m], amt[m] / c24[m], rtol=1e-3, atol=0.01)
print("OK: Average Amount Last 24 Hours == Amount Last 24 Hours / Transactions Last 24 Hours")
if ACCOUNT_AGE_BASIS == "sender":
    assert ((age == 0) == (since_cnt == 0)).all()
    print("OK: account age is 0 exactly when the sender has no earlier transaction")
tick("numeric / logical checks", T0)

# --- Independent brute-force cross-check (sampled SENDER accounts), all sender-based columns ---
rng = np.random.default_rng(42)
counts = np.bincount(sender_codes)
cand = np.flatnonzero((counts >= 30) & (counts <= 400))
if cand.size == 0:
    cand = np.argsort(counts)[::-1][:N_SAMPLE_ACCOUNTS]
picked = rng.choice(cand, size=min(N_SAMPLE_ACCOUNTS, cand.size), replace=False)

rows = np.flatnonzero(np.isin(sender_codes, picked))
rows = rows[np.argsort(sender_codes[rows], kind="stable")]
code_rows = sender_codes[rows]
bounds = np.flatnonzero(np.diff(code_rows)) + 1
for sl in np.split(np.arange(rows.size), bounds):
    g = code_rows[sl][0]
    order_g = np.lexsort((tid_arr[rows[sl]], ts_sec[rows[sl]]))       # (timestamp, Transaction ID)
    idx = rows[sl][order_g]
    tt, aa = ts_sec[idx], amount_paid[idx]
    diff = tt[:, None] - tt[None, :]                                    # t_i - t_j

    def brute_count(W):
        return ((diff > 0) & (diff < W)).sum(axis=1)                   # t - W < t_j < t

    exp_amt24 = (((diff > 0) & (diff < WINDOW_24H)) * aa[None, :]).sum(axis=1)
    exp_cnt24 = brute_count(WINDOW_24H)
    exp_avg = np.divide(exp_amt24, exp_cnt24, out=np.zeros(len(tt)), where=exp_cnt24 > 0)
    exp_tsp = np.concatenate([[np.nan], np.diff(tt).astype(float)])
    if ACCOUNT_AGE_BASIS == "sender":
        first = tt.min()
    else:
        first = ts_sec[(sender_codes == g) | (receiver_codes == g)].min()   # first appearance on either side

    assert np.array_equal(c10[idx], brute_count(WINDOW_10M))
    assert np.array_equal(c30[idx], brute_count(WINDOW_30M))
    assert np.array_equal(c1[idx], brute_count(WINDOW_1H))
    assert np.array_equal(c24[idx], exp_cnt24)
    assert np.array_equal(c7[idx], brute_count(WINDOW_7D))
    assert np.allclose(amt[idx], exp_amt24, rtol=1e-9, atol=0.01)
    assert np.allclose(tsp[idx], exp_tsp, equal_nan=True)
    assert np.array_equal(age[idx], tt - first)
    assert np.array_equal(since_cnt[idx], (diff > 0).sum(axis=1))
    assert np.allclose(since_amt[idx], ((diff > 0) * aa[None, :]).sum(axis=1), rtol=1e-9, atol=0.01)
    assert np.allclose(avg24[idx], exp_avg, rtol=1e-6, atol=0.01)
print(f"OK: brute-force check matched exactly on {picked.size} sampled sender accounts ({rows.size:,} transactions) for 11 sender-based columns")
tick("brute-force cross-check (sender)", T0)

# --- Independent brute-force cross-check (sampled RECEIVER accounts), column 15 ---
rcounts = np.bincount(receiver_codes)
rcand = np.flatnonzero((rcounts >= 30) & (rcounts <= 400))
if rcand.size == 0:
    rcand = np.argsort(rcounts)[::-1][:N_SAMPLE_ACCOUNTS]
rpicked = rng.choice(rcand, size=min(N_SAMPLE_ACCOUNTS, rcand.size), replace=False)
rrows = np.flatnonzero(np.isin(receiver_codes, rpicked))
rrows = rrows[np.argsort(receiver_codes[rrows], kind="stable")]
rcode_rows = receiver_codes[rrows]
for sl in np.split(np.arange(rrows.size), np.flatnonzero(np.diff(rcode_rows)) + 1):
    order_g = np.lexsort((tid_arr[rrows[sl]], ts_sec[rrows[sl]]))
    idx = rrows[sl][order_g]
    tt = ts_sec[idx]
    diff = tt[:, None] - tt[None, :]
    assert np.array_equal(rcv10[idx], ((diff > 0) & (diff < WINDOW_10M)).sum(axis=1))
print(f"OK: brute-force check matched exactly on {rpicked.size} sampled receiver accounts ({rrows.size:,} transactions) for column 15")
tick("brute-force cross-check (receiver)", T0)

# --- FUTURE-INVARIANCE TEST: delete every transaction after a cut-off time and recompute.
#     If any feature of an earlier transaction changes, that feature used future information.
cut_ts = int(np.percentile(ts_sec, 60))
keep = ts_sec <= cut_ts
res_sub = compute_temporal_features(sender_codes[keep], receiver_codes[keep], ts_sec[keep], amount_paid[keep], tid[keep], ACCOUNT_AGE_BASIS)
for k, v_sub in res_sub.items():
    v_full = res[k][keep]
    ok = np.allclose(v_full, v_sub, rtol=1e-9, atol=1e-6, equal_nan=True)
    assert ok, f"Feature '{k}' changes when future transactions are removed -> it uses future information!"
print(f"OK: FUTURE-INVARIANCE test passed - removing all {int((~keep).sum()):,} transactions after {pd.to_datetime(cut_ts, unit='s')} "
      f"changes none of the {int(keep.sum()):,} earlier rows' features (all 12 numeric features).")
del res_sub, keep
tick("future-invariance test", T0)

# --- Optional: coverage against LI-Small_accounts.csv (slow, off by default)
if RUN_ACCOUNTS_COVERAGE:
    acc = pd.read_csv(ACCOUNTS_FILE, usecols=["Bank ID", "Account Number"], dtype=str)
    acc_ids = pd.Index(acc["Bank ID"] + "_" + acc["Account Number"])
    cov = tf["Sender Account ID"].cat.categories.isin(acc_ids).mean() * 100
    print(f"Info: {cov:.2f}% of distinct sender IDs are present in LI-Small_accounts.csv")
    del acc, acc_ids
    tick("accounts coverage", T0)

del c10, c30, c1, c24, c7, amt, tsp, age, since_cnt, since_amt, avg24, rcv10, rows, rrows, code_rows, rcode_rows, res
gc.collect()
print(f"\nALL VALIDATION CHECKS PASSED  (total {time.time() - T0:,.1f} s)")

======================================================================
VALIDATION
======================================================================
Raw rows                : 6,924,049
Invalid timestamps      : 0 (excluded)
Valid rows              : 6,924,049
temporal_features rows  : 6,924,049
OK: rows == valid transaction rows
OK: Transaction ID is unique and ascending
OK: Transaction ID covers 1..6,924,049
OK: exactly the 15 required columns, in the required order
   [  0.0 s] schema / IDs

Missing values per column:
Transaction ID                                0
Sender Account ID                             0
Receiver Account ID                           0
Transactions Last 10 Minutes                  0
Transactions Last 30 Minutes                  0
Transactions Last 1 Hour                      0
Transactions Last 24 Hours                    0
Transactions Last 7 Days                      0
Amount Last 24 Hours                          0
Time Since Previous Transaction          681283
Account Age Before Transaction                0
Transactions Since First Seen                 0
Amount Since First Seen                       0
Average Amount Last 24 Hours                  0
Transactions Last 10 Minutes Receiver         0

Unique senders: 681,283 | NaN in Time Since Previous: 681,283
OK: NaN only in Time Since Previous Transaction, exactly once per sender
   [  0.8 s] missing values
OK: all counts / amounts / times are >= 0
OK: 10 min <= 30 min <= 1 hour <= 24 hours <= 7 days for every row
OK: Transactions Last 7 Days <= Transactions Since First Seen
OK: Amount Last 24 Hours <= Amount Since First Seen
OK: zero 24h count -> zero 24h amount and zero 24h average
OK: Average Amount Last 24 Hours == Amount Last 24 Hours / Transactions Last 24 Hours
   [  1.1 s] numeric / logical checks
OK: brute-force check matched exactly on 25 sampled sender accounts (1,583 transactions) for 11 sender-based columns
   [  1.5 s] brute-force cross-check (sender)
OK: brute-force check matched exactly on 25 sampled receiver accounts (967 transactions) for column 15
   [  1.5 s] brute-force cross-check (receiver)
OK: FUTURE-INVARIANCE test passed - removing all 2,769,190 transactions after 2022-09-06 13:32:00 changes none of the 4,154,859 earlier rows' features (all 12 numeric features).
   [  6.1 s] future-invariance test

ALL VALIDATION CHECKS PASSED  (total 6.2 s)

In [10]:
from IPython.display import display

print("First 20 rows of temporal_features:")
display(temporal_features.head(20))

print("\nSummary statistics of the numeric columns:")
display(temporal_features.drop(columns=["Transaction ID", "Sender Account ID", "Receiver Account ID"]).describe().T)

# Manual-inspection view: sender accounts with several transactions
cnts = temporal_features["Sender Account ID"].value_counts()
sample_accounts = list(cnts[(cnts >= 10) & (cnts <= 60)].index[:3]) or list(cnts.index[:3])

DEBUG_COLS = ["Transaction ID", "Sender Account ID", "Timestamp"] + FINAL_COLUMNS[3:]
for acct in sample_accounts:
    msk = (temporal_features["Sender Account ID"] == acct).to_numpy()
    dbg = temporal_features.loc[msk].copy()
    dbg["Timestamp"] = ts_debug[msk].to_numpy()          # debug only, not in final output
    dbg["Amount Paid (current)"] = amt_debug[msk].to_numpy()
    dbg = dbg.sort_values(["Timestamp", "Transaction ID"])[DEBUG_COLS + ["Amount Paid (current)"]]
    print(f"\nSender account: {acct}  ({len(dbg)} transactions)")
    display(dbg.head(15))

First 20 rows of temporal_features:

,Transaction ID,Sender Account ID,Receiver Account ID,Transactions Last 10 Minutes,Transactions Last 30 Minutes,Transactions Last 1 Hour,Transactions Last 24 Hours,Transactions Last 7 Days,Amount Last 24 Hours,Time Since Previous Transaction,Account Age Before Transaction,Transactions Since First Seen,Amount Since First Seen,Average Amount Last 24 Hours,Transactions Last 10 Minutes Receiver
0,1,011_8000ECA90,011_8000ECA90,2,2,2,2,2,592593.97,60.0,480,2,592593.97,296296.985,2
1,2,03402_80021DAD0,03402_80021DAD0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
2,3,011_8000ECA90,001120_8006AA910,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
3,4,03814_8006AD080,03814_8006AD080,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
4,5,020_8006AD530,020_8006AD530,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
5,6,012_8006ADD30,012_8006ADD30,0,2,2,2,2,2208375.71,1440.0,1440,2,2208375.71,1104187.855,0
6,7,011_800059120,01217_8006AD4E0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,1
7,8,011_8000ECA90,011_8000ECA90,1,1,1,1,1,592571.00,420.0,420,1,592571.00,592571.000,1
8,9,001120_8006AA910,0243166_81470DCF0,0,0,0,0,0,0.00,NaN,1680,0,0.00,0.000,0
9,10,01217_8006AD4E0,01217_8006AD4E0,0,0,0,0,0,0.00,NaN,600,0,0.00,0.000,2
10,11,0224_8006AD580,023319_80567ED00,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
11,12,00394_8006AF210,0214342_805586EA0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
12,13,03618_800929EA0,001277_800929EF0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,2
13,14,00394_80093BDB0,021414_80092A6C0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
14,15,01291_80092A730,01291_80092A730,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
15,16,01231_800B69730,011265_80092AC50,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
16,17,00394_80093BDB0,00394_80093BDB0,1,1,1,1,1,64335.00,360.0,360,1,64335.00,64335.000,0
17,18,01231_800B69730,021414_80093CED0,1,1,1,1,1,1986.00,180.0,180,1,1986.00,1986.000,0
18,19,020_800952940,020_800952940,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
19,20,031811_800A8FCD0,031811_800A8FCD0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0

Summary statistics of the numeric columns:

,count,mean,std,min,25%,50%,75%,max
Transactions Last 10 Minutes,6924049.0,8.422256e+00,3.764045e+01,0.0,0.0000,0.000,1.00,9.700000e+02
Transactions Last 30 Minutes,6924049.0,2.616547e+01,1.125399e+02,0.0,0.0000,0.000,1.00,3.060000e+03
Transactions Last 1 Hour,6924049.0,5.165227e+01,2.166159e+02,0.0,0.0000,1.000,1.00,3.780000e+03
Transactions Last 24 Hours,6924049.0,1.112202e+03,4.681014e+03,0.0,1.0000,3.000,8.00,3.483500e+04
Transactions Last 7 Days,6924049.0,4.858140e+03,2.194478e+04,0.0,4.0000,15.000,37.00,1.580610e+05
Amount Last 24 Hours,6924049.0,1.111030e+09,1.418639e+10,0.0,56.3000,9891.550,288261.06,3.679700e+12
Time Since Previous Transaction,6242766.0,3.764822e+04,1.022555e+05,0.0,240.0000,960.000,32520.00,1.150380e+06
Account Age Before Transaction,6924049.0,3.609298e+05,2.707104e+05,0.0,87900.0000,382680.000,604800.00,1.437240e+06
Transactions Since First Seen,6924049.0,5.405047e+03,2.519274e+04,0.0,4.0000,16.000,41.00,2.220310e+05
Amount Since First Seen,6924049.0,6.789734e+09,5.330471e+10,0.0,7837.6900,226159.460,3683778.55,3.679701e+12
Average Amount Last 24 Hours,6924049.0,3.723897e+06,4.133901e+08,0.0,25.5457,2268.847,54466.81,3.341723e+11
Transactions Last 10 Minutes Receiver,6924049.0,4.101177e-01,1.230928e+00,0.0,0.0000,0.000,1.00,4.000000e+01

Sender account: 000_8001263A0  (60 transactions)

,Transaction ID,Sender Account ID,Timestamp,Transactions Last 10 Minutes,Transactions Last 30 Minutes,Transactions Last 1 Hour,Transactions Last 24 Hours,Transactions Last 7 Days,Amount Last 24 Hours,Time Since Previous Transaction,Account Age Before Transaction,Transactions Since First Seen,Amount Since First Seen,Average Amount Last 24 Hours,Transactions Last 10 Minutes Receiver,Amount Paid (current)
918892,918893,000_8001263A0,2022-09-01 10:30:00,0,0,0,0,0,0.00,NaN,0,0,0.00,0.0000,0,8036.08
918893,918894,000_8001263A0,2022-09-01 10:42:00,0,1,1,1,1,8036.08,720.0,720,1,8036.08,8036.0800,0,37977.25
918891,918892,000_8001263A0,2022-09-01 10:52:00,0,2,2,2,2,46013.33,600.0,1320,2,46013.33,23006.6650,0,67531.01
1190974,1190975,000_8001263A0,2022-09-01 16:32:00,0,0,0,3,3,113544.34,20400.0,21720,3,113544.34,37848.1133,0,458.41
1190975,1190976,000_8001263A0,2022-09-01 16:41:00,1,1,1,4,4,114002.75,540.0,22260,4,114002.75,28500.6875,1,481.55
1487256,1487257,000_8001263A0,2022-09-01 23:03:00,0,0,0,5,5,114484.30,22920.0,45180,5,114484.30,22896.8600,0,1121.20
1487255,1487256,000_8001263A0,2022-09-01 23:17:00,0,1,1,6,6,115605.50,840.0,46020,6,115605.50,19267.5833,0,1140.46
1678199,1678200,000_8001263A0,2022-09-02 03:02:00,0,0,0,7,7,116745.96,13500.0,59520,7,116745.96,16677.9943,0,41918.27
1678200,1678201,000_8001263A0,2022-09-02 03:10:00,1,1,1,8,8,158664.23,480.0,60000,8,158664.23,19833.0288,1,10309.78
1869375,1869376,000_8001263A0,2022-09-02 07:34:00,0,0,0,9,9,168974.01,15840.0,75840,9,168974.01,18774.8900,0,458.41
1869376,1869377,000_8001263A0,2022-09-02 07:46:00,0,1,1,10,10,169432.42,720.0,76560,10,169432.42,16943.2420,0,481.55
1930275,1930276,000_8001263A0,2022-09-02 09:05:00,0,0,0,11,11,169913.97,4740.0,81300,11,169913.97,15446.7245,0,1140.46
1930276,1930277,000_8001263A0,2022-09-02 09:13:00,1,1,1,12,12,171054.43,480.0,81780,12,171054.43,14254.5358,1,1121.20
2291710,2291711,000_8001263A0,2022-09-02 17:36:00,0,0,0,8,13,57691.33,30180.0,111960,13,172175.63,7211.4162,0,8036.08
2291711,2291712,000_8001263A0,2022-09-02 17:43:00,1,1,1,9,14,65727.41,420.0,112380,14,180211.71,7303.0456,1,37977.25

Sender account: 000_800274EB0  (60 transactions)

,Transaction ID,Sender Account ID,Timestamp,Transactions Last 10 Minutes,Transactions Last 30 Minutes,Transactions Last 1 Hour,Transactions Last 24 Hours,Transactions Last 7 Days,Amount Last 24 Hours,Time Since Previous Transaction,Account Age Before Transaction,Transactions Since First Seen,Amount Since First Seen,Average Amount Last 24 Hours,Transactions Last 10 Minutes Receiver,Amount Paid (current)
166444,166445,000_800274EB0,2022-09-01 00:06:00,0,0,0,0,0,0.00,NaN,0,0,0.00,0.0000,0,41865.20
983328,983329,000_800274EB0,2022-09-01 12:14:00,0,0,0,1,1,41865.20,43680.0,43680,1,41865.20,41865.2000,0,13884.16
983329,983330,000_800274EB0,2022-09-01 12:18:00,1,1,1,2,2,55749.36,240.0,43920,2,55749.36,27874.6800,1,366349.43
983327,983328,000_800274EB0,2022-09-01 12:27:00,1,2,2,3,3,422098.79,540.0,44460,3,422098.79,140699.5967,1,95356.47
1258050,1258051,000_800274EB0,2022-09-01 18:02:00,0,0,0,4,4,517455.26,20100.0,64560,4,517455.26,129363.8150,0,69.00
1258048,1258049,000_800274EB0,2022-09-01 18:04:00,1,1,1,5,5,517524.26,120.0,64680,5,517524.26,103504.8520,1,1511.90
1258051,1258052,000_800274EB0,2022-09-01 18:06:00,2,2,2,6,6,519036.16,120.0,64800,6,519036.16,86506.0267,2,87.13
1258049,1258050,000_800274EB0,2022-09-01 18:14:00,1,3,3,7,7,519123.29,480.0,65280,7,519123.29,74160.4700,1,1931.27
1867878,1867879,000_800274EB0,2022-09-02 07:33:00,0,0,0,7,8,479189.36,47940.0,113220,8,521054.56,68455.6229,0,1931.27
1867879,1867880,000_800274EB0,2022-09-02 07:34:00,1,1,1,8,9,481120.63,60.0,113280,9,522985.83,60140.0787,1,69.00
1867880,1867881,000_800274EB0,2022-09-02 07:40:00,2,2,2,9,10,481189.63,360.0,113640,10,523054.83,53465.5144,2,87.13
1867877,1867878,000_800274EB0,2022-09-02 07:54:00,0,3,3,10,11,481276.76,840.0,114480,11,523141.96,48127.6760,0,1511.90
2203182,2203183,000_800274EB0,2022-09-02 15:32:00,0,0,0,8,12,7198.60,27480.0,141960,12,524653.86,899.8250,0,29.14
2203178,2203179,000_800274EB0,2022-09-02 15:33:00,1,1,1,9,13,7227.74,60.0,142020,13,524683.00,803.0822,1,1220.11
2203179,2203180,000_800274EB0,2022-09-02 15:38:00,2,2,2,10,14,8447.85,300.0,142320,14,525903.11,844.7850,2,1302.77

Sender account: 000_80084E3C0  (60 transactions)

,Transaction ID,Sender Account ID,Timestamp,Transactions Last 10 Minutes,Transactions Last 30 Minutes,Transactions Last 1 Hour,Transactions Last 24 Hours,Transactions Last 7 Days,Amount Last 24 Hours,Time Since Previous Transaction,Account Age Before Transaction,Transactions Since First Seen,Amount Since First Seen,Average Amount Last 24 Hours,Transactions Last 10 Minutes Receiver,Amount Paid (current)
174442,174443,000_80084E3C0,2022-09-01 00:00:00,0,0,0,0,0,0.00,NaN,0,0,0.00,0.0000,0,352.77
174441,174442,000_80084E3C0,2022-09-01 00:17:00,0,1,1,1,1,352.77,1020.0,1020,1,352.77,352.7700,0,393.75
460995,460996,000_80084E3C0,2022-09-01 00:31:00,0,1,2,2,2,746.52,840.0,1860,2,746.52,373.2600,1,751.01
460994,460995,000_80084E3C0,2022-09-01 00:32:00,1,2,3,3,3,1497.53,60.0,1920,3,1497.53,499.1767,2,904.85
594012,594013,000_80084E3C0,2022-09-01 03:34:00,0,0,0,4,4,2402.38,10920.0,12840,4,2402.38,600.5950,0,268.00
594010,594011,000_80084E3C0,2022-09-01 03:40:00,1,1,1,5,5,2670.38,360.0,13200,5,2670.38,534.0760,1,903.06
594011,594012,000_80084E3C0,2022-09-01 03:55:00,0,2,2,6,6,3573.44,900.0,14100,6,3573.44,595.5733,0,192.18
1762782,1762783,000_80084E3C0,2022-09-02 05:05:00,0,0,0,0,7,0.00,90600.0,104700,7,3765.62,0.0000,0,393.75
1762527,1762528,000_80084E3C0,2022-09-02 05:06:00,1,1,1,1,8,393.75,60.0,104760,8,4159.37,393.7500,1,903.06
1762528,1762529,000_80084E3C0,2022-09-02 05:11:00,2,2,2,2,9,1296.81,300.0,105060,9,5062.43,648.4050,1,192.18
1762783,1762784,000_80084E3C0,2022-09-02 05:13:00,3,3,3,3,10,1488.99,120.0,105180,10,5254.61,496.3300,1,352.77
1762529,1762530,000_80084E3C0,2022-09-02 05:20:00,2,4,4,4,11,1841.76,420.0,105600,11,5607.38,460.4400,1,268.00
1868132,1868133,000_80084E3C0,2022-09-02 07:46:00,0,0,0,5,12,2109.76,8760.0,114360,12,5875.38,421.9520,0,195.66
1868131,1868132,000_80084E3C0,2022-09-02 07:50:00,1,1,1,6,13,2305.42,240.0,114600,13,6071.04,384.2367,1,32145.35
2164868,2164869,000_80084E3C0,2022-09-02 14:54:00,0,0,0,7,14,34450.77,25440.0,140040,14,38216.39,4921.5386,0,245.72

In [11]:
t_start = time.time()

# Keep the previous (8-column) file instead of silently overwriting it
if BACKUP_OLD_FILE and os.path.exists(OUTPUT_FILE):
    if os.path.exists(BACKUP_FILE):
        os.remove(BACKUP_FILE)
    os.rename(OUTPUT_FILE, BACKUP_FILE)
    print("Previous file kept as:", os.path.abspath(BACKUP_FILE))

temporal_features.to_csv(OUTPUT_FILE, index=False)

print("Saved successfully:")
print(os.path.abspath(OUTPUT_FILE))
print("\nFinal shape:")
print(temporal_features.shape)
print(f"File size: {os.path.getsize(OUTPUT_FILE) / 1024**2:,.1f} MB | write time: {time.time() - t_start:,.1f} s")

# Quick read-back sanity check
check = pd.read_csv(OUTPUT_FILE, nrows=5)
assert list(check.columns) == FINAL_COLUMNS
assert len(check.columns) == 15
display(check)

Saved successfully:
e:\AML-GNN-Project\data\processed\temporal_features.csv

Final shape:
(6924049, 15)
File size: 647.0 MB | write time: 74.8 s

,Transaction ID,Sender Account ID,Receiver Account ID,Transactions Last 10 Minutes,Transactions Last 30 Minutes,Transactions Last 1 Hour,Transactions Last 24 Hours,Transactions Last 7 Days,Amount Last 24 Hours,Time Since Previous Transaction,Account Age Before Transaction,Transactions Since First Seen,Amount Since First Seen,Average Amount Last 24 Hours,Transactions Last 10 Minutes Receiver
0,1,011_8000ECA90,011_8000ECA90,2,2,2,2,2,592593.97,60.0,480,2,592593.97,296296.985,2
1,2,03402_80021DAD0,03402_80021DAD0,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
2,3,011_8000ECA90,001120_8006AA910,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
3,4,03814_8006AD080,03814_8006AD080,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0
4,5,020_8006AD530,020_8006AD530,0,0,0,0,0,0.00,NaN,0,0,0.00,0.000,0